### ISSUE TITLE
Write "Build in Public" section

### ISSUE THREAD

**Issue by aassoiants** [aassoiants/bitcoin-ux-research-toolkit#10]
![Image](https://user-images.githubusercontent.com/90313394/228249675-b3acbc3c-8431-422a-b280-9dc3876e1eea.png)

**Description of the content**
This section of the UX research toolkit is dedicated to a write up on building in public as a way to get feedback and insights as we build. 

**Link to the google doc**
[Googledoc](https://docs.google.com/document/d/1Wr_8nekqYnCpxqFBldGcBRVNiur4Y3yG8tvLJUKwnDc/edit?usp=sharing)

**Format**
- Benefits of working in public
- How to build in public
- Resources

**Who's working on this right now?**
@GBKS 

**Can I contribute and how?**
TBD

**Comment by jakey-ads** [comment]
Just added a few minor suggestions :) But I like it! Lots of helpful references for the reader
