### ISSUE TITLE
Write "Moderated Usability Tests" section

### ISSUE THREAD

**Issue by aassoiants** [aassoiants/bitcoin-ux-research-toolkit#12]
![Image](https://user-images.githubusercontent.com/90313394/229776657-8e6b46cc-fd4c-4fd0-bda6-c1c487fae011.png)

**Description of the content**
Moderated usability tests is the process  where a person uses the interface we have built and we observe them using the interface. 

**Link to the google doc**
[Google doc](https://docs.google.com/document/d/1ku191kKKCi2gOTFuqP1s6WxN-9TV7U_5clG8DJdaRNA/edit#heading=h.9oj1xkknra1x)

**Format**
The current format outlines:

- Why to use this method
- How doing this method with bitcoin and lighting products is unique
- Outlines the process
- Additional resources

**Who's working on this right now?**
@mouxdesign @stackingsaunter 

**Can I contribute and how?**
This write up is open for contributions.
You can contribute by commenting on the Google doc

**Comment by mouxdesign** [comment]
Draft version of the usability testing write up [here.](https://docs.google.com/document/d/1ku191kKKCi2gOTFuqP1s6WxN-9TV7U_5clG8DJdaRNA/edit?usp=sharing).

Feel free to comment on the google doc.

**Comment by mouxdesign** [comment]
@stackingsaunter @HonzaMikula Have created a draft outline on this method so far. Feel free to comment on the google doc!

**Comment by stackingsaunter** [comment]
@mouxdesign great start! Left some comments and will try to expand some sections with what I created for TrustToken [(1) ](https://docs.google.com/document/d/1sOYwGhgH02w3tsj6OzGTRWEA-kkYSBjXWJfJ_ULQ2LQ/edit#heading=h.gjdgxs) [(2)](https://docs.google.com/document/d/1zGcYHxgkTVrJzLy1AgUe9rXx-w5nCWdklZ5jkj0KHu8/edit#heading=h.jp30k554ssst) [(3)](https://docs.google.com/document/d/1SjSsduVaBXfMWV1uq5CsifCV4ziMAF0Ps4lG5Mw-xDc/edit#heading=h.y18i0dwqlemk)

**Comment by mouxdesign** [comment]
Further fleshed out this write up.

[Googledoc](https://docs.google.com/document/d/1ku191kKKCi2gOTFuqP1s6WxN-9TV7U_5clG8DJdaRNA/edit#)

What's been added:
- A sprint format which was provided by Jakub in the examples
- Unique challenges and ways in which this is suitable for bitcoin/lightning products
- A visual

Still to do:

- [ ] - Usability testing script
- [ ] - Usability testing plan doc
- [ ] - Examples/links to pre-screening questions
- [ ] - Examples of outreach message

**Comment by Noyi-24-7** [comment]
Hey @mouxdesign! Went through this and it’s really awesome, noticed you had a space for a script for conducting the usability test sessions and I went ahead to create some drafts of them, with questions, I put them in a notion file…hope this helps 😅

Here it is - [https://www.notion.so/Usability-Test-Scripts-adc0cdf5f3e54930bcbee0834e35e012?pvs=4](https://www.notion.so/Usability-Test-Scripts-adc0cdf5f3e54930bcbee0834e35e012)

I got some of the ideas I used to structure these questions from this UX Research Toolkit - [https://www.figma.com/file/4CiQdFmBUamloCnbeIAVyO/UX-Research-Toolkit?node-id=2%3A5&t=eYoiJcCA6ESV61Dv-1](https://www.figma.com/file/4CiQdFmBUamloCnbeIAVyO/UX-Research-Toolkit?node-id=2%3A5&t=eYoiJcCA6ESV61Dv-1)

I just made them more “bitcoin centric” so to speak.

**Comment by mouxdesign** [comment]
@Noyi-24-7 Thank you so much for your contribution. I was trying to access the Notion link however it seemed to require access. Could you make the link publicly viewable?

**Comment by Noyi-24-7** [comment]
> @Noyi-24-7 Thank you so much for your contribution. I was trying to access the Notion link however it seemed to require access. Could you make the link publicly viewable?

Ohh...my bad, I forgot to give public access, I just did now, so you can check it out, sorry about that 😅

**Comment by mouxdesign** [comment]
Thanks for the comments on this one. I have further iterated on the write up for the usability testing process. @Noyi-24-7 will look at those docs you provided as well.

**Comment by mouxdesign** [comment]
Worked on this one a bit more we now have:
[- Process](https://docs.google.com/document/d/1ku191kKKCi2gOTFuqP1s6WxN-9TV7U_5clG8DJdaRNA/edit#)
- [Usability test script](https://docs.google.com/document/d/10IE5gRz_68oFlg0z5ol8Mg__Qp5g28a0XjefB9bzj-w/edit#)
- Outreach message (included in the write up)

To add in:

- [ ] Pre-screening questions

**Comment by stackingsaunter** [comment]
Please review my [screener template](https://docs.google.com/document/d/1mgaqh0OacV9wG5W9WtlC6tp-oyMPNENaFg-pIo-JSUY/edit#heading=h.nq5ta981kc2c)

**Comment by stackingsaunter** [comment]
Thanks Mo, opened
