### ISSUE TITLE
Write "Design Sprints" section

### ISSUE THREAD

**Issue by aassoiants** [aassoiants/bitcoin-ux-research-toolkit#13]
![Image](https://user-images.githubusercontent.com/90313394/228250441-9ea5ff75-bbc3-41d9-afbf-5c9791b10797.png)

**Description of the content**
This write up will cover the process of doing a design sprint as a method to solve the question: 
How do we come up with solutions to the problems users are facing?

**Link to the google doc**
**to be added

**Format**
This will outline the step by step process of doing a design sprint with the end outcome being that:
- Users pain points from user research are then solved/ideated on together by the team 
- Use cases of when it's best to do the sprint

**Who's working on this right now?**
@HonzaMikula @mouxdesign 

**Can I contribute and how?**
This is open for contributors. You can contribute by commenting/suggesting edits to the Googledoc
[Write up template](https://docs.google.com/document/d/1ju6EKEKExKOnUxhv9scAEIlE35I4R4OU3Jq-LSaDuWg/edit# )

**Comment by aassoiants** [comment]
@mouxdesign 
- Any feedback from Johns?
- Is Leticia interested in joining our repo?

**Comment by mouxdesign** [comment]
Leticia is more than happy to join the repo. Feel free to add her, her Github name is: ledoss

**Comment by mouxdesign** [comment]
Adding n the draft version of the write up for this one.

[Draft](https://docs.google.com/document/d/1cUFqQddWY0F9xnsLXgNlnJ6BmCMacJw9R92hehV5Gzo/edit#)
