### ISSUE TITLE
Write "Repository" section

### ISSUE THREAD

**Issue by mouxdesign** [aassoiants/bitcoin-ux-research-toolkit#14]
![Image](https://user-images.githubusercontent.com/90313394/228250660-17660638-27e8-457c-afec-a1915f2dba38.png)

**Description of the content**
This section will outline the process of setting up a UX research repository. A repository that will act as an information source over a long term for a team to refer to when solving particular usability issues in an interface. 

**Link to the google doc**
**to be added

**Format**
This will outline how to set up a repository.
Why using a repository is useful to a team.
Resources

**Who's working on this right now?**
**to be added

**Can I contribute and how?**
This is open to contributions. 
You can contribute by commenting on the Googledoc.

[Write up template](https://docs.google.com/document/d/1ju6EKEKExKOnUxhv9scAEIlE35I4R4OU3Jq-LSaDuWg/edit# )

**Comment by mouxdesign** [comment]
Worked on a [draft](https://docs.google.com/document/d/1tZ4RmTfsp2gcMAYjuj8ziCoHwr8doQR_A5VXHanHsi8/edit?usp=sharing) for this one as well.

And to test the idea practically created something for Bitcoin Core App to store the research insights that will collected over the next few weeks.

**Comment by mouxdesign** [comment]
Worked further on this section:
- Added in a visual of how a repository looks
- Link on how to do an affinity diagram

**Comment by jakey-ads** [comment]
Hey, I've added some comments/suggestions in case worth considering :)
