### ISSUE TITLE
Write "Communicating to your project team" section

### ISSUE THREAD

**Issue by mouxdesign** [aassoiants/bitcoin-ux-research-toolkit#17]
![Image](https://user-images.githubusercontent.com/90313394/228250855-ff2e9c29-5215-4916-94d8-f08987f46e10.png)

**Description of the content**
Help open source bitcoin and lighting projects learn more about ways and methods that they can communicate the research insights to the rest of the team.

**Link to the google doc**
Started writing a draft version of this one as well. Needs visuals and bunch more work on the content.
[Google doc](https://docs.google.com/document/d/1nfuU8s8GRO15WII98jui2v7tCd4SvK3w2faI7Tb2Rpk/edit?usp=sharing)

**Format**
This would outline an approach as to how teams can share the research findings in a way that is:

- Unique to working in open source projects
- Relevant to bitcoin/lightning projects
- Example orientated (showing examples used in the past)

**Who's working on this right now?**
@mouxdesign 

**Can I contribute and how?**
This is open for everyone to contribute to. You can do so by commenting directing in the Google document.

**Comment by mouxdesign** [comment]
Started writing a draft version of this one as well. Needs visuals and bunch more work on the content.
[Google doc](https://docs.google.com/document/d/1nfuU8s8GRO15WII98jui2v7tCd4SvK3w2faI7Tb2Rpk/edit?usp=sharing)

**Comment by aassoiants** [comment]
Added comments in the doc, great work

**Comment by GBKS** [comment]
Also left a few comments. As Art pointed out, the title should probably be adjusted (see discussion in the doc).

**Comment by jakey-ads** [comment]
Hey guys, I'm fairly new to the community so looking to start contributing more where I can. I've added some thoughts/suggestions which are hopefully useful. Overall think it's solid

**Comment by aassoiants** [comment]
Great to have you @jakey-ads ! Looking through the project plan and adding gentle suggestions is a great way to begin participating. 

Are you in our discord group? Would you be able to join us in next Thursday's UX Research call?

**Comment by jakey-ads** [comment]
Thanks @aassoiants. Great to be here :)

Next Thursday's call I'll be working so may struggle. Hoping to join what I can going forward, but have been starting to make my way through previous recordings on Youtube regardless. 

I've joined the Discord too 💯

**Comment by stackingsaunter** [comment]
Great work, added minor suggestions
