### ISSUE TITLE
Write method: Rapid prototyping

### ISSUE THREAD

**Issue by aassoiants** [aassoiants/bitcoin-ux-research-toolkit#8]
![Image](https://user-images.githubusercontent.com/90313394/228250976-22210c40-5564-499b-b5a9-4f9b6223fe02.png)

**Description of the content**
Rapid prototyping is the methos where you create a high fidelity prototype and test out that prototype on users.

**Link to the google doc**
- https://miro.com/app/board/uXjVMYd_5hY=/?share_link_id=224524131430

**Format**
- Why to use this method
- How doing this method with bitcoin and lighting products is unique
- Outlines the process
- Additional resources

**Who's working on this right now?**
@aassoiants 

**Can I contribute and how?**
[Template](https://docs.google.com/document/d/1ju6EKEKExKOnUxhv9scAEIlE35I4R4OU3Jq-LSaDuWg/edit#)

**Comment by mouxdesign** [comment]
@aassoiants You made some really great content already on this topic in the presentation that you did during the last UX research call. 

Created this rough draft based on the content you already created. Its a rough draft with the following:
- Background
- The goals
- Benefits of this process
- Steps

[[Link to draft](https://docs.google.com/document/d/1an88-_enwYj8pJ7I2HbnUol5W0bemt1KCHoFyHyuTOY/edit?usp=sharing)]

**Comment by mouxdesign** [comment]
@aassoiants Would love a review on this one.
